### ISSUE TITLE
Use Cypress caching for utility jobs

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/code-coverage#163]
these jobs could use the existing pre-installed workspace
```yml
jobs:
  unit:
    description: Checks the code formatting
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run format:check

  publish:
    description: Publishes the new version of the plugin to NPM
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run semantic-release
```
