### ISSUE TITLE
nyc config `all:true` does not work

### ISSUE THREAD

**Issue by penx** [cypress-io/code-coverage#194]
**Versions**

- What is this plugin's version? 3.2.1
- What is Cypress version? 4.4.0
- What is your operating system? Mac OS X 10.15.4
- What is the Node version? 12.14.1
- What is the NPM version? 6.13.4

**Describe the bug**
 
If I have the following in my package.json:

```yml
  "nyc": {
    "report-dir": "coverage/integration",
    "all": true,
    "include": ["src/**/*.js"],
    "exclude": ["**/*.test.js", "**/*.stories.js"]
  }
```

**Logs and screenshots**
![Screenshot 2020-04-16 at 17 23 59](https://user-images.githubusercontent.com/1027024/79481210-1396d580-8007-11ea-8bdd-d7eb4a68c20c.png)

Note that design-system coverage is 100% but hasn't included all files in this folder.

**Link to the repo**
https://github.com/penx/storybook-code-coverage

```sh
yarn
yarn coverage:integration
open coverage/integration/lcov-report/index.html
```

---
side note - is it possible to put the nyc config for cypress anywhere other than package.json? I am using nyc for multiple reports and would rather not store the cypress-specific config in a shared location. Just checking if this would be a feature request.
