### ISSUE TITLE
Cypress component test crashes within github actions

### ISSUE THREAD

**Issue by AndersPfyl** [cypress-io/code-coverage#703]
**Logs and screenshots**
![image](https://github.com/cypress-io/code-coverage/assets/16819719/7eea6fff-1dc7-4890-a7bc-a202106c213c)

**Versions**

- What is this plugin's version? `3.12.3`
- What is Cypress version? `13.3.0`
- What is your operating system? Github runner uses: `ubuntu-latest-8-cores`
    - Ubuntu 22.04.3 LTS
- What is the shell? `bash`
- What is the Node version? `16.20.2`
- How do you instrument your application? `Instanbul`
    - `.babelrc` contains: `{"presets": ["next/babel"], "plugins": ["istanbul"]}` 
- When running tests, if you open the web application in regular browser, and open DevTools, do you see `window.__coverage__` object? Can you paste a screenshot?
    - Coverage works locally (see screenshots), but issue is on runner.
    - ![image](https://github.com/cypress-io/code-coverage/assets/16819719/3a107fdb-561a-48a3-9197-b6c37ce92d6d)
    - ![image](https://github.com/cypress-io/code-coverage/assets/16819719/54efd8a5-1c07-45f7-8d78-8aa464a8dc83)
- Is there `.nyc_output` folder? Is there `.nyc_output/out.json` file. Is it empty? Can you paste at least part of it so we can see the keys and file paths?
    - ![image](https://github.com/cypress-io/code-coverage/assets/16819719/ce4e41f0-d361-4d58-9f54-7eaf77765459)
- Do you have any custom NYC settings? No
- Do you run Cypress tests in a Docker container? The runner does

**Describe the bug**
I have tried adding code coverage to our cypress tests. The coverage works locally but when running within github actions it seems the addition of instrumentation causes cypress to crash with the error `There was an error reconnecting to the Chrome DevTools protocol. Please restart the browser.` after the first cypress test tries to run. 

**Link to the repo**
Our repo is private and confidential, this will limit some things I can share to help troubleshoot the issue.

**Comment by MikeMcC399** [comment]
@AndersPfyl 

Can you post also your GitHub Actions workflow?

Note that Node.js `16` is no longer supported. It entered [end-of-life recently](https://nodejs.org/en/blog/announcements/nodejs16-eol) on Sep 11, 2023.

**Comment by AndersPfyl** [comment]
@MikeMcC399 
Workflow: 
```
steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Typescript Dependencies
        uses: ./.github/actions/test_ts
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create babelrc
        working-directory: app
        shell: bash
        run: |
          touch .babelrc
          echo '{"presets": ["next/babel"], "plugins": ["istanbul"]}' > .babelrc
      - uses: ./.github/actions/integration
```
integration action:
```
steps:
    - name: Run tests
      working-directory: app
      env:
        TZ: UTC
        # for msw
        API_ENDPOINT: ...
      shell: sh
      run: |
        ./node_modules/.bin/cypress run --component
```

We're waiting for node to have LTS on 20 before we upgrade - Do you think this be the cause of the issue?
